// Per-map cell dimensions for the marker placement math. Ragnarok
// minimap UIs rescale to fit any map size, so a cell coord like
// (234, 185) lands at a different fractional position depending on
// the map's actual width/height. Without this table we'd have to
// assume one constant grid size for every map — which is wrong by
// the ratio (actual_size / assumed_size) and visibly off-centres
// the cross.
//
// Source: OpenKore FLD2 field files (~1300 maps, cell-accurate).
// The table lives in `map-dimensions-data.ts` and is regenerated by
// `scripts/extract-map-dimensions.mjs`. Maps not listed (private-
// server customs, very new official content) fall back to the
// auto-observed bounds the addon collects from packets — see
// `effectiveMapDimensions` below.

import { KNOWN_MAP_DIMENSIONS } from "./map-dimensions-data";

export type MapDimensions = { width: number; height: number };

export const DEFAULT_MAP_SIZE = 256;
const DEFAULT_DIMS: MapDimensions = {
  width: DEFAULT_MAP_SIZE,
  height: DEFAULT_MAP_SIZE,
};

/** Look up a map's true (width, height) in cells. Returns the
 *  default for unlisted maps so the marker still renders, just
 *  potentially off-position. */
export function getMapDimensions(mapName: string): MapDimensions {
  return KNOWN_MAP_DIMENSIONS[mapName] ?? DEFAULT_DIMS;
}

/** Best-effort map dimensions combining the hardcoded table and
 *  the addon's own observations of the highest cell coords seen
 *  on that map (warps + walking steps). For unlisted maps this is
 *  the only source of dimensions — without it, an unknown map
 *  would always render at the assumed-256 default and a teleport
 *  marker at cell (290, 240) would clamp to the right edge. With
 *  observations, the dimension grows as the player explores and
 *  marker placement self-corrects.
 *
 *  Rules:
 *    - Known map, no observations → hardcoded value.
 *    - Known map, observations exceed hardcoded → use observed
 *      (the hardcoded value is wrong; player has been further
 *      than it claimed).
 *    - Unknown map → observed + small buffer (the player almost
 *      certainly hasn't visited every cell, so the true max is at
 *      least a few cells beyond what we've seen).
 *    - Unknown map with no observations → 256×256 fallback. */
export function effectiveMapDimensions(
  mapName: string,
  observed?: { maxX: number; maxY: number },
): MapDimensions {
  const hardcoded = KNOWN_MAP_DIMENSIONS[mapName];
  if (!observed) return hardcoded ?? DEFAULT_DIMS;
  if (!hardcoded) {
    // The player has been at (maxX, maxY) so the map is at least
    // that big; round up to the next 10 cells as a buffer for
    // unobserved space near the edges.
    const pad = 10;
    return {
      width: Math.max(observed.maxX + pad, 100),
      height: Math.max(observed.maxY + pad, 100),
    };
  }
  return {
    width: Math.max(hardcoded.width, observed.maxX + 1),
    height: Math.max(hardcoded.height, observed.maxY + 1),
  };
}
